CREATE DATABASE lgn_db;
USE lgn_db;
CREATE TABLE users (
  u_id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(100) NOT NULL DEFAULT '',
  pass VARCHAR(100) NOT NULL DEFAULT '',
  is_locked INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (u_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;